<?php

use Drupal\pragmatica\Entity\SourceType;

/**
 * Implements hook_install().
 */
function pragmatica_install() {
  $types = [
    1 => 'Texto',
    2 => 'Áudio',
    // 3 => 'Documento (PDF)'
    // 4 => 'Vídeo'
    // 5 => 'Imagem'
  ];


  foreach ($types as $id => $label) {
    if (!Drupal::entityTypeManager()->getStorage('pragmatica_source_type')->load($id)) {
      $type = SourceType::create([
        'id' => $id,
        'name' => $label,
      ]);
      $type->save();
    }
  }

}
